title: AAIMC-OC Consortium
description: Application of AI defined Molecular Classifications in Ovarian Cancer
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
  - members.md
  - research.md
  - contact.md

# Add Google Fonts
google_fonts: "Open+Sans:400,600,700|Roboto:400,500,700"

# Social links (optional)
# twitter_username: username
# github_username:  username
# linkedin_username: username

# Build settings
markdown: kramdown 
